import PDFDocument from 'pdfkit';
import fs from 'fs';

export const generatePDF = (report, patient) => {
    const doc = new PDFDocument();
    const filePath = `./reports/${report._id}.pdf`;
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);


    doc.fontSize(24)
        .fillColor('#1a73e8')
        .text('BioTech DC Lab Report', { align: 'center' })
        .moveDown(1);

    doc.fontSize(18)
        .fillColor('#333333')
        .text('Patient Information', { underline: true })
        .moveDown(0.5)
        .fillColor('black')
        .fontSize(14)
        .text(`Name: ${patient.name}`)
        .text(`Age: ${patient.age}`)
        .text(`Gender: ${patient.gender}`)
        .text(`Address: ${patient.address}`)
        .moveDown(1);


    report.reports.forEach((testReport) => {
        const test = testReport.tests[0];
        doc.fontSize(16)
            .fillColor('#1a73e8')
            .text(test.name, { underline: true })
            .moveDown(0.5)
            .fillColor('#333333')
            .fontSize(14)
            .text(`Description: ${test.description}`)
            .text(`Normal Range: ${test.normalRange}`)
            .text(`Abnormal Range: ${test.abnormalRange}`)
            .fillColor('#e91e63')
            .text(`Result: ${testReport.result}`)
            .fillColor('#333333')
            .text(`Units: ${testReport.unit}`)
            .moveDown(1);
    });


    doc.fontSize(10)
        .fillColor('#1a73e8')
        .text('Generated by BioTech DC Lab Management System', { align: 'center', opacity: 0.5 });


    doc.end();

    return filePath;
};
